config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :physics_bodies
  resources :universes, except: [:index, :new]
  resources :simulations

  # Defines the root path route ("/")
  root 'simulations#index'
end

app/models/simulation.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: simulations
#
#  id               :uuid             not null, primary key
#  computation_time :decimal(, )
#  computed_at      :datetime
#  name             :text             not null
#  slug             :text
#  solver_method    :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_simulations_on_name  (name) UNIQUE
#  index_simulations_on_slug  (slug) UNIQUE
#
class Simulation < ApplicationRecord
  has_rich_text :description
  has_one :universe, inverse_of: :simulation, dependent: :destroy
  has_many :physics_bodies, inverse_of: :simulation, dependent: :destroy

  accepts_nested_attributes_for :universe
  accepts_nested_attributes_for :physics_bodies, allow_destroy: true, reject_if: proc { |attr| attr['name'].blank? }

  validates :name, :solver_method, presence: true
  validates :name, uniqueness: true

  # Use the name attribute as the slug in this models URLs.
  extend FriendlyId
  friendly_id :name, use: :history

  def should_generate_new_friendly_id?
    slug.blank? or name_changed?
  end

  def solved?
    self.computed_at.present? and self.computation_time.present?
  end
end

app/controllers/simulations_controller.rb
# frozen_string_literal: true

# Defines all available HTTP actions for simulations.
class SimulationsController < ApplicationController
  before_action :set_simulation, only: [:show, :edit, :update, :destroy]

  # GET /simulations or /simulations.json
  def index
    @simulations = Simulation.all
  end

  # GET /simulations/1 or /simulations/1.json
  def show
    # Pass the Physics Bodies states to Javascript for rendering.
    gon.physics_bodies = []

    if @simulation.solved?
      gon.solved = true

      @simulation.physics_bodies.each do |physics_body|
        gon.physics_bodies << {
          name: physics_body.name,
          positions: physics_body.positions,
          velocities: physics_body.velocities
        }
      end
    else
      gon.solved = false

      @simulation.physics_bodies.each do |physics_body|
        gon.physics_bodies << {
          name: physics_body.name,
          radius: physics_body.radius,
          initial_position_x: physics_body.initial_position_x,
          initial_position_y: physics_body.initial_position_y,
          initial_position_z: physics_body.initial_position_z,
          initial_velocity_x: physics_body.initial_velocity_x,
          initial_velocity_y: physics_body.initial_velocity_y,
          initial_velocity_z: physics_body.initial_velocity_z
        }
      end
    end

    # Redirect to the latest URL if an old URL was used.
    redirect_to @simulation, status: :moved_permanently unless request.path == simulation_path(@simulation)
  end

  # GET /simulations/new
  def new
    @simulation = Simulation.new
    @simulation.build_universe
  end

  # GET /simulations/1/edit
  def edit; end

  # POST /simulations or /simulations.json
  def create
    @simulation = Simulation.new(simulation_params)

    respond_to do |format|
      if @simulation.save
        format.html { redirect_to simulation_url(@simulation), notice: 'Simulation was successfully created.' }
        format.json { render :show, status: :created, location: @simulation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simulations/1 or /simulations/1.json
  def update
    respond_to do |format|
      if @simulation.update(simulation_params)
        format.html { redirect_to simulation_url(@simulation), notice: 'Simulation was successfully updated.' }
        format.json { render :show, status: :ok, location: @simulation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simulations/1 or /simulations/1.json
  def destroy
    @simulation.destroy

    respond_to do |format|
      format.html { redirect_to simulations_url, notice: 'Simulation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_simulation
    @simulation = Simulation.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Render the 404 page if a slug was used that doesn't match any records.
    render file: "#{Rails.root}/public/404.html", status: :not_found and return
  end

  # Only allow a list of trusted parameters through.
  def simulation_params
    params.require(:simulation).permit(:name, :slug, :description, :solver_method, :computation_time, :computed_at,
                                       universe_attributes: [
                                         :_destroy, :id, :start_time, :end_time, :timestep, :number_of_timesteps
                                       ], physics_bodies_attributes: [
                                         :_destroy, :id, :name, :description,
                                         :initial_position_x, :initial_position_y, :initial_position_z,
                                         :initial_velocity_x, :initial_velocity_y, :initial_velocity_z
                                       ])
  end
end

app/helpers/simulations_helper.rb
# frozen_string_literal: true

# Defines helper methods specific to simulations.
module SimulationsHelper
end

app/views/simulations/_form.html.erb
<%= form_with(model: simulation, class: "contents") do |form| %>
  <% if simulation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(simulation.errors.count, "error") %> prohibited this simulation from being saved:</h2>

      <ul>
        <% simulation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="text-lg">Asterisks (*) indicates fields that are required.</h3>

  <div class="my-5">
    <%= form.label :name, 'Name *' %>
    <%= form.text_area :name, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :solver_method, 'Solver Method *' %>
    <%= form.text_area :solver_method, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <h2 class="font-bold text-2xl">Timesteps</h2>
  <%= form.fields_for :universe do |universe_form| %>
    <h3 class="text-lg">Only 3 out of 4 time fields are required, the missing value will be automatically calculated. If all 4 values are supplied, they must match the equation: <br><em><b>(EndTime - StartTime) / NumberOfTimesteps == Timestep</b></em></h3>
    <div class="my-5">
      <%= universe_form.label :start_time, 'Start Time (seconds)' %>
      <br><em>(Default is 0 seconds)</em>
      <%= universe_form.text_field :start_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= universe_form.label :end_time, 'End Time (seconds)' %>
      <%= universe_form.text_field :end_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= universe_form.label :timestep, 'Timestep (seconds)' %>
      <%= universe_form.text_field :timestep, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= universe_form.label :number_of_timesteps, 'Number of Timesteps' %>
      <%= universe_form.number_field :number_of_timesteps, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  <% end %>

  <h2 class="font-bold text-2xl">Add Physics Bodies</h2>
  <div data-controller="nested-form">
    <template data-target='nested-form.template'>
      <%= form.fields_for :physics_bodies, PhysicsBody.new, child_index: 'TEMPLATE_RECORD' do |physics_body| %>
        <%= render 'physics_bodies/nested_form_fields', form: physics_body %>
      <% end %>
    </template>

    <%= form.fields_for :physics_bodies do |physics_body| %>
      <%= render 'physics_bodies/nested_form_fields', form: physics_body %>
    <% end %>

    <div data-target="nested-form.add_item">
      <%= link_to "Add Physics Body", "#", data: { action: "nested-form#add_association" }, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
    </div>
  </div>
  <br>
  <hr>
  <br>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/simulations/_simulation.html.erb
<div id="<%= dom_id simulation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= simulation.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= simulation.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Solver method:</strong>
    <%= simulation.solver_method %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Number of Physics Bodies:</strong>
    <%= simulation.physics_bodies.count %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Computation time:</strong>
    <%= simulation.computation_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Computed at:</strong>
    <%= simulation.computed_at %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this simulation", simulation, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this simulation', edit_simulation_path(simulation), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/simulations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing Simulation</h1>

  <%= render "form", simulation: @simulation %>

  <%= link_to "Show this simulation", @simulation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to simulations", simulations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/simulations/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Simulations</h1>
    <%= link_to 'New Simulation', new_simulation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="simulations" class="min-w-full">
    <%= render @simulations %>
  </div>
</div>

app/views/simulations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Simulation</h1>

  <%= render "form", simulation: @simulation %>

  <%= link_to 'Cancel', simulations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/simulations/show.html.erb
<div class="mx-auto w-full flex flex-col">
  <div class="mx-auto">
    <%= render @simulation %>

    <%= link_to 'Edit this simulation', edit_simulation_path(@simulation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this simulation', simulation_path(@simulation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to simulations', simulations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
  <canvas id="simulation_renderer" class="w-full border-grey border-2 m-2"></canvas>
</div>