config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :physics_bodies
  resources :universes, except: [:index, :new]
  resources :simulations

  # Defines the root path route ("/")
  root 'simulations#index'
end

app/controllers/universes_controller.rb
# frozen_string_literal: true

# Defines all available HTTP actions for simulations.
class UniversesController < ApplicationController
  before_action :set_universe, only: [:show, :edit, :update, :destroy]

  # GET /universes/1 or /universes/1.json
  def show; end

  # GET /universes/1/edit
  def edit; end

  # POST /universes or /universes.json
  def create
    @universe = Universe.new(universe_params)

    respond_to do |format|
      if @universe.save
        format.html { redirect_to universe_url(@universe), notice: 'Universe was successfully created.' }
        format.json { render :show, status: :created, location: @universe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @universe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universes/1 or /universes/1.json
  def update
    respond_to do |format|
      if @universe.update(universe_params)
        format.html { redirect_to universe_url(@universe), notice: 'Universe was successfully updated.' }
        format.json { render :show, status: :ok, location: @universe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @universe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universes/1 or /universes/1.json
  def destroy
    @universe.destroy

    respond_to do |format|
      format.html { redirect_to universes_url, notice: 'Universe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_universe
    @universe = Universe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def universe_params
    params.require(:universe).permit(:simulation_id, :start_time, :end_time, :timestep, :number_of_timesteps)
  end
end

app/helpers/universes_helper.rb
# frozen_string_literal: true

# Defines helper methods specific to simulations.
module UniversesHelper
end

app/views/universes/_form.html.erb
<%= form_with(model: universe, class: "contents") do |form| %>
  <% if universe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(universe.errors.count, "error") %> prohibited this universe from being saved:</h2>

      <ul>
        <% universe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :start_time %>
    <%= form.text_field :start_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_time %>
    <%= form.text_field :end_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :timestep %>
    <%= form.text_field :timestep, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :number_of_timesteps %>
    <%= form.number_field :number_of_timesteps, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :timesteps %>
    <%= form.text_field :timesteps, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/universes/_universe.html.erb
<div id="<%= dom_id universe %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Simulation:</strong>
    <%= universe.simulation_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start time:</strong>
    <%= universe.start_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End time:</strong>
    <%= universe.end_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Timestep:</strong>
    <%= universe.timestep %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Number of timesteps:</strong>
    <%= universe.number_of_timesteps %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Timesteps:</strong>
    <%= universe.timesteps %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this universe", universe, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this universe', edit_universe_path(universe), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/universes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing Universe</h1>

  <%= render "form", universe: @universe %>

  <%= link_to "Show this universe", @universe, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to universes", universes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/universes/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Universes</h1>
    <%= link_to 'New universe', new_universe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="universes" class="min-w-full">
    <%= render @universes %>
  </div>
</div>

app/views/universes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @universe %>

    <%= link_to 'Edit this universe', edit_universe_path(@universe), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this universe', universe_path(@universe), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to universes', universes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>