config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :physics_bodies
  resources :universes, except: [:index, :new]
  resources :simulations

  # Defines the root path route ("/")
  root 'simulations#index'
end

app/models/physics_body.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: physics_bodies
#
#  id                 :uuid             not null, primary key
#  accelerations_x    :decimal(, )      default([]), is an Array
#  accelerations_y    :decimal(, )      default([]), is an Array
#  accelerations_z    :decimal(, )      default([]), is an Array
#  forces_x           :decimal(, )      default([]), is an Array
#  forces_y           :decimal(, )      default([]), is an Array
#  forces_z           :decimal(, )      default([]), is an Array
#  gm                 :decimal(, )
#  initial_position_x :decimal(, )      not null
#  initial_position_y :decimal(, )      not null
#  initial_position_z :decimal(, )      not null
#  initial_velocity_x :decimal(, )      not null
#  initial_velocity_y :decimal(, )      not null
#  initial_velocity_z :decimal(, )      not null
#  name               :text             not null
#  positions_x        :decimal(, )      default([]), is an Array
#  positions_y        :decimal(, )      default([]), is an Array
#  positions_z        :decimal(, )      default([]), is an Array
#  radius             :decimal(, )      not null
#  slug               :text
#  type               :text
#  velocities_x       :decimal(, )      default([]), is an Array
#  velocities_y       :decimal(, )      default([]), is an Array
#  velocities_z       :decimal(, )      default([]), is an Array
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  simulation_id      :uuid             not null
#
# Indexes
#
#  index_physics_bodies_on_name           (name) UNIQUE
#  index_physics_bodies_on_simulation_id  (simulation_id)
#  index_physics_bodies_on_slug           (slug) UNIQUE
#
# Foreign Keys
#
#  fk_rails_0453254253  (simulation_id => simulations.id)
#
class PhysicsBody < ApplicationRecord
  has_rich_text :description

  belongs_to :simulation, inverse_of: :physics_bodies

  validates :name, :radius, :initial_position_x, :initial_position_y, :initial_position_z,
            :initial_velocity_x, :initial_velocity_y, :initial_velocity_z, presence: true
  validates :name, uniqueness: true

  after_create :initialize_state_arrays

  # Use the name attribute as the slug in this models URLs.
  extend FriendlyId
  friendly_id :name, use: :history

  def should_generate_new_friendly_id?
    slug.blank? or name_changed?
  end

  def initial_position
    [self.initial_position_x, self.initial_position_y, self.initial_position_z]
  end

  def initial_velocity
    [self.initial_velocity_x, self.initial_velocity_y, self.initial_velocity_z]
  end

  def positions
    l = self.simulation.universe.number_of_timesteps
    positions_array = Array.new(l, nil)

    l.times do |t|
      positions_array[t] = [self.positions_x[t], self.positions_y[t], self.positions_z[t]]
    end

    positions_array
  end

  def velocities
    l = self.simulation.universe.number_of_timesteps
    velocities_array = Array.new(l, nil)

    l.times do |t|
      velocities_array[t] = [self.velocities_x[t], self.velocities_y[t], self.velocities_z[t]]
    end

    velocities_array
  end

  def accelerations
    l = self.simulation.universe.number_of_timesteps
    accelerations_array = Array.new(l, nil)

    l.times do |t|
      accelerations_array[t] = [self.accelerations_x[t], self.accelerations_y[t], self.accelerations_z[t]]
    end

    accelerations_array
  end

  def forces
    l = self.simulation.universe.number_of_timesteps
    forces_array = Array.new(l, nil)

    l.times do |t|
      forces_array[t] = [self.forces_x[t], self.forces_y[t], self.forces_z[t]]
    end

    forces_array
  end

  private

  # Initialize the state arrays with the correct length.
  def initialize_state_arrays
    l = self.simulation.universe.number_of_timesteps

    self.positions_x = Array.new(l, nil)
    self.positions_y = Array.new(l, nil)
    self.positions_z = Array.new(l, nil)
    self.velocities_x = Array.new(l, nil)
    self.velocities_y = Array.new(l, nil)
    self.velocities_z = Array.new(l, nil)
    self.accelerations_x = Array.new(l, nil)
    self.accelerations_y = Array.new(l, nil)
    self.accelerations_z = Array.new(l, nil)
    self.forces_x = Array.new(l, nil)
    self.forces_y = Array.new(l, nil)
    self.forces_z = Array.new(l, nil)
  end
end

app/controllers/physics_bodies_controller.rb
# frozen_string_literal: true

# Defines all available HTTP actions for physics bodies.
class PhysicsBodiesController < ApplicationController
  before_action :set_physics_body, only: [:show, :edit, :update, :destroy]

  # GET /physics_bodies or /physics_bodies.json
  def index
    @physics_bodies = PhysicsBody.all
  end

  # GET /physics_bodies/1 or /physics_bodies/1.json
  def show
    # Redirect to the latest URL if an old URL was used.
    redirect_to @physics_body, status: :moved_permanently unless request.path == physics_body_path(@physics_body)
  end

  # GET /physics_bodies/new
  def new
    @physics_body = PhysicsBody.new
  end

  # GET /physics_bodies/1/edit
  def edit; end

  # POST /physics_bodies or /physics_bodies.json
  def create
    @physics_body = PhysicsBody.new(physics_body_params)

    respond_to do |format|
      if @physics_body.save
        format.html { redirect_to physics_body_url(@physics_body), notice: 'Physics body was successfully created.' }
        format.json { render :show, status: :created, location: @physics_body }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @physics_body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physics_bodies/1 or /physics_bodies/1.json
  def update
    respond_to do |format|
      if @physics_body.update(physics_body_params)
        format.html { redirect_to physics_body_url(@physics_body), notice: 'Physics body was successfully updated.' }
        format.json { render :show, status: :ok, location: @physics_body }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @physics_body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physics_bodies/1 or /physics_bodies/1.json
  def destroy
    @physics_body.destroy

    respond_to do |format|
      format.html { redirect_to physics_bodies_url, notice: 'Physics body was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_physics_body
    @physics_body = PhysicsBody.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Render the 404 page if a slug was used that doesn't match any records.
    render file: "#{Rails.root}/public/404.html", status: :not_found and return
  end

  # Only allow a list of trusted parameters through.
  def physics_body_params
    params.require(:physics_body).permit(:simulation_id, :name, :description,
                                         :initial_position_x, :initial_position_y, :initial_position_z,
                                         :initial_velocity_x, :initial_velocity_y, :initial_velocity_z)
  end
end

app/helpers/physics_bodies_helper.rb
# frozen_string_literal: true

# Defines helper methods specific to physics bodies.
module PhysicsBodiesHelper
end

app/views/physics_bodies/_form.html.erb
<%= form_with(model: physics_body, class: "contents") do |form| %>
  <% if physics_body.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(physics_body.errors.count, "error") %> prohibited this physics_body from being saved:</h2>

      <ul>
        <% physics_body.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :simulation_id %>
    <%= form.text_field :simulation_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_area :name, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  
<div class="my-5">
    <%= form.label :radius %>
    <%= form.text_field :radius, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :slug %>
    <%= form.text_area :slug, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :initial_position_x %>
    <%= form.text_field :initial_position_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :initial_position_y %>
    <%= form.text_field :initial_position_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :initial_position_z %>
    <%= form.text_field :initial_position_z, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :initial_velocity_x %>
    <%= form.text_field :initial_velocity_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :initial_velocity_y %>
    <%= form.text_field :initial_velocity_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :initial_velocity_z %>
    <%= form.text_field :initial_velocity_z, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :positions_x %>
    <%= form.text_field :positions_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :positions_y %>
    <%= form.text_field :positions_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :positions_z %>
    <%= form.text_field :positions_z, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :velocities_x %>
    <%= form.text_field :velocities_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :velocities_y %>
    <%= form.text_field :velocities_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :velocities_z %>
    <%= form.text_field :velocities_z, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :accelerations_x %>
    <%= form.text_field :accelerations_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :accelerations_y %>
    <%= form.text_field :accelerations_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :accelerations_z %>
    <%= form.text_field :accelerations_z, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :forces_x %>
    <%= form.text_field :forces_x, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :forces_y %>
    <%= form.text_field :forces_y, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :forces_z %>
    <%= form.text_field :forces_z, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/physics_bodies/_nested_form_fields.html.erb
<div class='nested-fields border-grey border-2 rounded-lg px-2'>
  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <div class="my-5">
      <%= form.label :name, 'Physics Body Name *' %>
      <%= form.text_area :name, rows: 1, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :description %>
      <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :initial_position_x, 'Initial Position (kilometers) *' %>
      <div class="w-full">
        <%= form.text_field :initial_position_x, placeholder: 'x', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-1/4" %>
        <%= form.text_field :initial_position_z, placeholder: 'z', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-1/4" %>
        <%= form.text_field :initial_position_y, placeholder: 'y', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-1/4" %>
      </div>
    </div>

    <div class="my-5">
      <%= form.label :initial_velocity_x, 'Initial Velocity (meters per second) *' %>
      <div class="w-full">
        <%= form.text_field :initial_velocity_x, placeholder: 'x', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-1/4" %>
        <%= form.text_field :initial_velocity_y, placeholder: 'y', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-1/4" %>
        <%= form.text_field :initial_velocity_z, placeholder: 'z', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-1/4" %>
      </div>
    </div>

    <%= link_to "Delete", "#", data: { action: "click->nested-form#remove_association" }, class: "ml-2 rounded-lg py-3 px-5 bg-red-600 inline-block text-white font-semibold" %>
  </div>
  <br>
</div>
<br>

app/views/physics_bodies/_physics_body.html.erb
<div id="<%= dom_id physics_body %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Simulation:</strong>
    <%= physics_body.simulation_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= physics_body.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= physics_body.slug %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= physics_body.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Initial position x:</strong>
    <%= physics_body.initial_position_x %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Initial position y:</strong>
    <%= physics_body.initial_position_y %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Initial position z:</strong>
    <%= physics_body.initial_position_z %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Initial velocity x:</strong>
    <%= physics_body.initial_velocity_x %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Initial velocity y:</strong>
    <%= physics_body.initial_velocity_y %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Initial velocity z:</strong>
    <%= physics_body.initial_velocity_z %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Positions x:</strong>
    <%= physics_body.positions_x %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Positions y:</strong>
    <%= physics_body.positions_y %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Positions z:</strong>
    <%= physics_body.positions_z %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Velocities x:</strong>
    <%= physics_body.velocities_x %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Velocities y:</strong>
    <%= physics_body.velocities_y %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Velocities z:</strong>
    <%= physics_body.velocities_z %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Accelerations x:</strong>
    <%= physics_body.accelerations_x %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Accelerations y:</strong>
    <%= physics_body.accelerations_y %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Accelerations z:</strong>
    <%= physics_body.accelerations_z %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Forces x:</strong>
    <%= physics_body.forces_x %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Forces y:</strong>
    <%= physics_body.forces_y %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Forces z:</strong>
    <%= physics_body.forces_z %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this physics body", physics_body, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this physics body', edit_physics_body_path(physics_body), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/physics_bodies/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing Physics Body</h1>

  <%= render "form", physics_body: @physics_body %>

  <%= link_to "Show this physics body", @physics_body, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to physics bodies", physics_bodies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/physics_bodies/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Physics bodies</h1>
    <%= link_to 'New physics body', new_physics_body_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="physics_bodies" class="min-w-full">
    <%= render @physics_bodies %>
  </div>
</div>

app/views/physics_bodies/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Physics Body</h1>

  <%= render "form", physics_body: @physics_body %>

  <%= link_to 'Cancel', :back, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/physics_bodies/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @physics_body %>

    <%= link_to 'Edit this physics_body', edit_physics_body_path(@physics_body), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this physics_body', physics_body_path(@physics_body), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to physics_bodies', physics_bodies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>